#!/bin/bash

if [ -z "$1" ]
then
    echo "Please specify endpoint"
    exit 1;
fi

if [ -z "$2" ]
then
    echo "Please specify main account id"
    exit 1;
fi

if [ -z "$3" ]
then
    echo "Please specify analytics period"
    exit 1;
fi

ENDPOINT=$1
ACCOUNT_ID=$2
PERIOD_DATE=$3

generate () {
    REQUEST=$1
    OUTPUT=$2

    curl -s $REQUEST > $OUTPUT
}

# FINANCE
FINANCE_ENDPOINT=$ENDPOINT"/finance"
FINANCE_OUTPUT_DIR="mock/responses/finance"

rm -f $FINANCE_OUTPUT_DIR/*

if [ ! -d $FINANCE_OUTPUT_DIR ]; then
  mkdir -p $FINANCE_OUTPUT_DIR;
fi

ACCOUNTS_OUTPUT=$FINANCE_OUTPUT_DIR"/accounts.json"
generate $FINANCE_ENDPOINT"/accounts" $ACCOUNTS_OUTPUT

ACCOUNT_OUTPUT=$FINANCE_OUTPUT_DIR"/account.json"
generate $FINANCE_ENDPOINT"/accounts/"$ACCOUNT_ID $ACCOUNT_OUTPUT

ANALYTICS_OUTPUT=$FINANCE_OUTPUT_DIR"/analytics.json"
generate $FINANCE_ENDPOINT"/analytics" $ANALYTICS_OUTPUT

ANALYTICSPERIOD_OUTPUT=$FINANCE_OUTPUT_DIR"/analyticsPeriod.json"
generate $FINANCE_ENDPOINT"/analytics/period/"$PERIOD_DATE $ANALYTICSPERIOD_OUTPUT

# RELEASES
RELEASES_ENDPOINT=$ENDPOINT"/releases"
RELEASES_OUTPUT_DIR="mock/responses/releases"

if [ ! -d $RELEASES_OUTPUT_DIR ]; then
  mkdir -p $RELEASES_OUTPUT_DIR;
fi

RELEASES_OUTPUT=$RELEASES_OUTPUT_DIR"/index.json"
generate $RELEASES_ENDPOINT $RELEASES_OUTPUT
