#!/bin/bash

if [ -z "$1" ]
then
    echo "Please specify endpoint"
    exit 1;
fi

if [ -z "$2" ]
then
    echo "Please specify main account id"
    exit 1;
fi

ENDPOINT=$1
MAIN_ACCOUNT=$2

generate () {
    REQUEST=$1
    OUTPUT=$2

    echo -n "export default " > $OUTPUT
    echo -n $(curl -s $REQUEST | ./node_modules/json-to-js/index.js) >> $OUTPUT
    echo -n ";" >> $OUTPUT
}

# FINANCE

FINANCE_ENDPOINT=$ENDPOINT"/finance"
FINANCE_OUTPUT_DIR="src/ApiClient/mock/dump/finance"

# FINANCE - BALANCES
if [ ! -d $FINANCE_OUTPUT_DIR ]; then
  mkdir -p $FINANCE_OUTPUT_DIR;
fi

ACCOUNTS_OUTPUT=$FINANCE_OUTPUT_DIR"/accounts.js"
generate $FINANCE_ENDPOINT"/accounts" $ACCOUNTS_OUTPUT

STATEMENTS_OUTPUT=$FINANCE_OUTPUT_DIR"/statements.js"
generate $FINANCE_ENDPOINT"/accounts/"$MAIN_ACCOUNT"/statements" $STATEMENTS_OUTPUT

EXPENSES_OUTPUT=$FINANCE_OUTPUT_DIR"/categorized_expenses.js"
generate $FINANCE_ENDPOINT"/accounts/"$MAIN_ACCOUNT"/expenses" $EXPENSES_OUTPUT
